/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uzbrain_mame4droid_UzbrainnetNative */

#ifndef _Included_com_uzbrain_mame4droid_UzbrainnetNative
#define _Included_com_uzbrain_mame4droid_UzbrainnetNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    oneLineParsing
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_oneLineParsing
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getAxValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getAxValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getAyValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getAyValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getAzValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getAzValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getGxValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getGxValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getGyValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getGyValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getGzValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getGzValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getLeftButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getLeftButton
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getRightButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getRightButton
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getModeButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getModeButton
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getPowerButton
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getPowerButton
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getBatteryValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getBatteryValue
  (JNIEnv *, jobject);

/*
 * Class:     com_uzbrain_mame4droid_UzbrainnetNative
 * Method:    getTimeStamp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_uzbrain_mame4droid_UzbrainnetNative_getTimeStamp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
